### ISSUE TITLE
Lazy-Fill bucket

### ISSUE THREAD

**Issue by MementoRC** [bharel/asynciolimiter#3]
I am interested in having a filling bucket rather than a draining one. Would it make sense to derive from the Leaky and override '_maybe_lock()' and '_wake_up()', or would you advise a simpler method?

**Comment by bharel** [comment]
I usually wouldn't suggest overriding those as they're private and might change without notice (not that I'm planning to change it but still).

What do you mean by filling bucket though? What are you trying to achieve?

**Comment by MementoRC** [comment]
What I meant is that in my app, I may need to use a variety of limiters, so
if I want to have both, I would have a new class that inherit from yours
and in that class I'd override the methods, they can thus change in the
base class

One of the API that I use is using the lazy-fill method, it fills the
bucket with time instead of leaking it and uses the tokens in the bucket
per request instead of filling the bucket with requests. It is basically
the opposite (as far as i can understand it) to the Leaky method. I don't
see that there is a difference, but on the other hand, it seems to simple
to modify (even for me) that I would rather say "I use exactly what the API
say", rather than "Well, the rate limiter is theoretically the same" to my
code reviewers
Actually, you commented on another aiolimiter from mjpieters and another
user asked a PR: https://github.com/mjpieters/aiolimiter/pull/74, which was
summarily closed
Thanks a lot for your reply

**Comment by bharel** [comment]
Well it sounds exactly the same to be honest.

Full bucket in the API's algorithm is equivalent to an empty leaky bucket. Every 'tick' the leaky bucket drains until empty, and yours fills until full. The only difference that might be is the starting condition, but I believe the API starts like a full bucket, which is equivalent to an empty leaky bucket.

I can add documentation showing the exact similarities.

**Comment by MementoRC** [comment]
Thanks, I couldn't find a conceptual difference either. I don't know how
popular is the lazy-fill version, it could be helpful to mention it, for
general audience. We can close this issue, since it's not one
Regards

**Comment by bharel** [comment]
I can't seem to find any mention of it anywhere.

**Comment by MementoRC** [comment]
Just FYI, a few references. The API where I first saw it mentioned is
Coinbase
https://www.quinbay.com/blog/understanding-rate-limiting-algorithms
https://dev.to/satrobit/rate-limiting-using-the-token-bucket-algorithm-3cjh
Thanks for the discussion

**Comment by bharel** [comment]
Thank you.

So the algorithm is called token bucket, and according to [Wikipedia](https://en.m.wikipedia.org/w/index.php?title=Token_bucket&oldid=1108310780), it is exactly equivalent to the leaky bucket as a meter, meaning exact same input and exact same output with no difference at all :-)
