### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by vectro** [bharel/asynciolimiter#8]
It would be great if this module had type hints, so that it could be used in type-checked projects.

**Comment by bharel** [comment]
Sounds like a great idea. It's not too hard. Do you want to open a PR or shall I make one?

**Comment by vectro** [comment]
I do not have the bandwidth to take this on right now, if you are able to do it, go for it!

**Comment by bharel** [comment]
It's actually almost fully type hinted. Do you have an issue during usage?

**Comment by bharel** [comment]
Oh I think py.typed is missing because it's a single module package

**Comment by vectro** [comment]
That sounds right, mypy is giving me this error:
```
error: Skipping analyzing "asynciolimiter": module is installed, but missing library stubs or py.typed marker  [import]
```

**Comment by bharel** [comment]
Please check now. 1.1.0 released

**Comment by bharel** [comment]
I'm guessing this is done :-)
